; generated by Slic3r 1.3.0 on 2022-05-07 at 15:26:44

; external perimeters extrusion width = 0.67mm (0.54mm^3/s)
; perimeters extrusion width = 0.64mm (0.51mm^3/s)
; infill extrusion width = 0.64mm (0.77mm^3/s)
; solid infill extrusion width = 0.64mm (6.14mm^3/s)
; top infill extrusion width = 0.64mm (4.61mm^3/s)

M107
T0
G92 X0 Y0 Z0 E0  ;set coordinates to 0 
G92 E0

T0
M302 P1
; Filament gcode

G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
G1 Z0.600 F150.000
G92 E0
G1 Z0.750 F150.000
G1 X1.914 Y1.914 F150.000
G1 Z0.600 F150.000
G1 E0.500 F100
G1 F100.002
G1 X1.611 Y2.217 E0.526
G1 X0.847 Y2.607 E0.577
G1 X0.005 Y2.741 E0.628
G1 X-0.822 Y2.619 E0.678
G1 X-1.611 Y2.217 E0.732
G1 X-2.217 Y1.611 E0.783
G1 X-2.607 Y0.847 E0.835
G1 X-2.741 Y0.003 E0.886
G1 X-2.607 Y-0.847 E0.937
G1 X-2.217 Y-1.611 E0.989
G1 X-1.611 Y-2.217 E1.040
G1 X-0.847 Y-2.607 E1.092
G1 X0.000 Y-2.740 E1.143
G1 X0.847 Y-2.607 E1.195
G1 X1.611 Y-2.217 E1.246
G1 X2.217 Y-1.611 E1.298
G1 X2.607 Y-0.847 E1.349
G1 X2.741 Y-0.000 E1.400
G1 X2.607 Y0.847 E1.452
G1 X2.217 Y1.611 E1.503
G1 X1.979 Y1.849 E1.524
G1 X2.556 Y2.556 F150.000
G1 F100.002
G1 X2.152 Y2.961 E1.558
G1 X1.131 Y3.481 E1.627
G1 X-0.000 Y3.660 E1.695
G1 X-1.131 Y3.481 E1.764
G1 X-2.152 Y2.961 E1.833
G1 X-2.961 Y2.152 E1.901
G1 X-3.481 Y1.131 E1.970
G1 X-3.660 Y-0.000 E2.039
G1 X-3.481 Y-1.131 E2.108
G1 X-2.961 Y-2.152 E2.176
G1 X-2.152 Y-2.961 E2.245
G1 X-1.131 Y-3.481 E2.314
G1 X-0.000 Y-3.660 E2.382
G1 X1.131 Y-3.481 E2.451
G1 X2.152 Y-2.961 E2.520
G1 X2.961 Y-2.152 E2.589
G1 X3.481 Y-1.131 E2.657
G1 X3.660 Y-0.000 E2.726
G1 X3.481 Y1.131 E2.795
G1 X2.961 Y2.152 E2.863
G1 X2.621 Y2.492 E2.892
G1 X2.235 Y2.235 F150.000
G1 F100.002
G1 X1.880 Y2.588 E2.922
G1 X0.989 Y3.043 E2.982
G1 X-0.000 Y3.199 E3.042
G1 X-0.989 Y3.044 E3.103
G1 X-1.881 Y2.588 E3.163
G1 X-2.603 Y1.854 E3.224
G1 X-3.043 Y0.989 E3.283
G1 X-3.196 Y0.033 E3.341
G1 X-3.043 Y-0.989 E3.403
G1 X-2.588 Y-1.881 E3.463
G1 X-1.881 Y-2.588 E3.523
G1 X-0.959 Y-3.049 E3.585
G1 X-0.000 Y-3.199 E3.643
G1 X0.959 Y-3.049 E3.701
G1 X1.880 Y-2.588 E3.763
G1 X2.588 Y-1.881 E3.823
G1 X3.030 Y-1.016 E3.881
G1 X3.199 Y-0.000 E3.943
G1 X3.043 Y0.989 E4.003
G1 X2.588 Y1.880 E4.063
G1 X2.300 Y2.170 E4.088
G1 Z1.200 F150.000
G1 X1.914 Y1.914 F150.000
G1 F100.002
G1 X1.611 Y2.217 E4.113
G1 X0.847 Y2.607 E4.165
G1 X-0.000 Y2.741 E4.216
G1 X-0.847 Y2.607 E4.268
G1 X-1.611 Y2.217 E4.319
G1 X-2.217 Y1.611 E4.371
G1 X-2.607 Y0.847 E4.422
G1 X-2.741 Y0.000 E4.474
G1 X-2.607 Y-0.847 E4.525
G1 X-2.217 Y-1.611 E4.576
G1 X-1.611 Y-2.217 E4.628
G1 X-0.847 Y-2.607 E4.679
G1 X0.000 Y-2.740 E4.731
G1 X0.847 Y-2.607 E4.782
G1 X1.611 Y-2.217 E4.834
G1 X2.217 Y-1.611 E4.885
G1 X2.607 Y-0.847 E4.937
G1 X2.741 Y-0.000 E4.988
G1 X2.607 Y0.847 E5.039
G1 X2.217 Y1.611 E5.091
G1 X1.979 Y1.849 E5.111
G1 X2.556 Y2.556 F150.000
G1 F100.002
G1 X2.152 Y2.961 E5.145
G1 X1.131 Y3.481 E5.214
G1 X0.000 Y3.660 E5.283
G1 X-1.131 Y3.481 E5.352
G1 X-2.152 Y2.961 E5.420
G1 X-2.961 Y2.152 E5.489
G1 X-3.481 Y1.131 E5.558
G1 X-3.660 Y-0.000 E5.626
G1 X-3.481 Y-1.131 E5.695
G1 X-2.961 Y-2.152 E5.764
G1 X-2.152 Y-2.961 E5.833
G1 X-1.131 Y-3.481 E5.901
G1 X-0.000 Y-3.660 E5.970
G1 X1.131 Y-3.481 E6.039
G1 X2.152 Y-2.961 E6.107
G1 X2.961 Y-2.152 E6.176
G1 X3.481 Y-1.131 E6.245
G1 X3.660 Y-0.000 E6.314
G1 X3.481 Y1.131 E6.382
G1 X2.961 Y2.152 E6.451
G1 X2.621 Y2.492 E6.480
G1 X2.235 Y2.235 F150.000
G1 F150
G1 X1.881 Y2.588 E6.510
G1 X0.989 Y3.043 E6.570
G1 X0.000 Y3.199 E6.630
G1 X-0.989 Y3.043 E6.690
G1 X-1.881 Y2.588 E6.750
G1 X-2.588 Y1.881 E6.810
G1 X-3.049 Y0.959 E6.872
G1 X-3.199 Y-0.000 E6.930
G1 X-3.049 Y-0.959 E6.988
G1 X-2.588 Y-1.881 E7.050
G1 X-1.881 Y-2.588 E7.110
G1 X-0.959 Y-3.049 E7.172
G1 X-0.000 Y-3.199 E7.230
G1 X0.959 Y-3.049 E7.289
G1 X1.881 Y-2.588 E7.351
G1 X2.588 Y-1.881 E7.411
G1 X3.030 Y-1.016 E7.469
G1 X3.199 Y-0.000 E7.531
G1 X3.043 Y0.989 E7.591
G1 X2.588 Y1.881 E7.651
G1 X2.300 Y2.170 E7.675
G1 Z1.800 F150.000
G1 X1.914 Y1.914 F150.000
G1 F100.002
G1 X1.611 Y2.217 E7.701
G1 X0.847 Y2.607 E7.752
G1 X0.000 Y2.741 E7.804
G1 X-0.847 Y2.607 E7.855
G1 X-1.611 Y2.217 E7.907
G1 X-2.217 Y1.611 E7.958
G1 X-2.607 Y0.847 E8.010
G1 X-2.741 Y0.000 E8.061
G1 X-2.607 Y-0.847 E8.113
G1 X-2.217 Y-1.611 E8.164
G1 X-1.611 Y-2.217 E8.215
G1 X-0.847 Y-2.607 E8.267
G1 X-0.000 Y-2.740 E8.318
G1 X0.847 Y-2.607 E8.370
G1 X1.611 Y-2.217 E8.421
G1 X2.217 Y-1.611 E8.473
G1 X2.607 Y-0.847 E8.524
G1 X2.741 Y-0.000 E8.576
G1 X2.607 Y0.847 E8.627
G1 X2.217 Y1.611 E8.679
G1 X1.979 Y1.849 E8.699
G1 X2.556 Y2.556 F150.000
G1 F100.002
G1 X2.152 Y2.961 E8.733
G1 X1.131 Y3.481 E8.802
G1 X0.000 Y3.660 E8.871
G1 X-1.131 Y3.481 E8.939
G1 X-2.152 Y2.961 E9.008
G1 X-2.961 Y2.152 E9.077
G1 X-3.481 Y1.131 E9.145
G1 X-3.660 Y-0.000 E9.214
G1 X-3.481 Y-1.131 E9.283
G1 X-2.961 Y-2.152 E9.352
G1 X-2.152 Y-2.961 E9.420
G1 X-1.131 Y-3.481 E9.489
G1 X-0.000 Y-3.660 E9.558
G1 X1.131 Y-3.481 E9.626
G1 X2.152 Y-2.961 E9.695
G1 X2.961 Y-2.152 E9.764
G1 X3.481 Y-1.131 E9.832
G1 X3.660 Y0.000 E9.901
G1 X3.481 Y1.131 E9.970
G1 X2.961 Y2.152 E10.039
G1 X2.621 Y2.492 E10.067
G1 X2.235 Y2.235 F150.000
G1 F150
G1 X1.881 Y2.588 E10.097
G1 X0.989 Y3.043 E10.158
G1 X-0.000 Y3.199 E10.218
G1 X-0.989 Y3.043 E10.278
G1 X-1.881 Y2.588 E10.338
G1 X-2.588 Y1.880 E10.398
G1 X-3.049 Y0.959 E10.460
G1 X-3.199 Y-0.000 E10.518
G1 X-3.049 Y-0.959 E10.576
G1 X-2.588 Y-1.881 E10.638
G1 X-1.881 Y-2.588 E10.698
G1 X-0.959 Y-3.049 E10.760
G1 X-0.000 Y-3.199 E10.818
G1 X0.959 Y-3.049 E10.876
G1 X1.881 Y-2.588 E10.938
G1 X2.588 Y-1.881 E10.998
G1 X3.030 Y-1.016 E11.056
G1 X3.199 Y-0.000 E11.118
G1 X3.043 Y0.989 E11.178
G1 X2.588 Y1.881 E11.238
G1 X2.300 Y2.170 E11.263
M106 S173.4
G1 Z2.400 F150.000
G1 X1.914 Y1.914 F150.000
G1 F100.002
G1 X1.611 Y2.217 E11.289
G1 X0.847 Y2.607 E11.340
G1 X-0.000 Y2.741 E11.391
G1 X-0.847 Y2.607 E11.443
G1 X-1.611 Y2.217 E11.494
G1 X-2.217 Y1.611 E11.546
G1 X-2.607 Y0.847 E11.597
G1 X-2.741 Y-0.000 E11.649
G1 X-2.607 Y-0.847 E11.700
G1 X-2.217 Y-1.611 E11.752
G1 X-1.611 Y-2.217 E11.803
G1 X-0.847 Y-2.607 E11.854
G1 X-0.000 Y-2.740 E11.906
G1 X0.847 Y-2.607 E11.957
G1 X1.611 Y-2.217 E12.009
G1 X2.217 Y-1.611 E12.060
G1 X2.607 Y-0.847 E12.112
G1 X2.741 Y0.000 E12.163
G1 X2.607 Y0.847 E12.215
G1 X2.217 Y1.611 E12.266
G1 X1.979 Y1.849 E12.286
G1 X2.556 Y2.556 F150.000
G1 F100.002
G1 X2.152 Y2.961 E12.321
G1 X1.131 Y3.481 E12.389
G1 X-0.000 Y3.660 E12.458
G1 X-1.131 Y3.481 E12.527
G1 X-2.152 Y2.961 E12.596
G1 X-2.961 Y2.152 E12.664
G1 X-3.481 Y1.131 E12.733
G1 X-3.660 Y-0.000 E12.802
G1 X-3.481 Y-1.131 E12.870
G1 X-2.961 Y-2.152 E12.939
G1 X-2.152 Y-2.961 E13.008
G1 X-1.131 Y-3.481 E13.076
G1 X0.000 Y-3.660 E13.145
G1 X1.131 Y-3.481 E13.214
G1 X2.152 Y-2.961 E13.283
G1 X2.961 Y-2.152 E13.351
G1 X3.481 Y-1.131 E13.420
G1 X3.660 Y-0.000 E13.489
G1 X3.481 Y1.131 E13.557
G1 X2.961 Y2.152 E13.626
G1 X2.621 Y2.492 E13.655
G1 X2.235 Y2.235 F150.000
G1 F150
G1 X1.881 Y2.588 E13.685
G1 X0.989 Y3.043 E13.745
G1 X-0.000 Y3.199 E13.805
G1 X-0.989 Y3.043 E13.865
G1 X-1.881 Y2.588 E13.925
G1 X-2.588 Y1.881 E13.985
G1 X-3.049 Y0.959 E14.047
G1 X-3.199 Y-0.000 E14.105
G1 X-3.049 Y-0.959 E14.164
G1 X-2.588 Y-1.881 E14.225
G1 X-1.881 Y-2.588 E14.285
G1 X-0.959 Y-3.049 E14.347
G1 X0.000 Y-3.199 E14.406
G1 X0.959 Y-3.049 E14.464
G1 X1.881 Y-2.588 E14.526
G1 X2.588 Y-1.881 E14.586
G1 X3.030 Y-1.016 E14.644
G1 X3.199 Y-0.000 E14.706
G1 X3.043 Y0.989 E14.766
G1 X2.588 Y1.880 E14.826
G1 X2.300 Y2.170 E14.850
G1 Z3.000 F150.000
G1 X1.914 Y1.914 F150.000
G1 F100.002
G1 X1.611 Y2.217 E14.876
G1 X0.847 Y2.607 E14.928
G1 X0.000 Y2.741 E14.979
G1 X-0.847 Y2.607 E15.030
G1 X-1.611 Y2.217 E15.082
G1 X-2.217 Y1.611 E15.133
G1 X-2.607 Y0.847 E15.185
G1 X-2.741 Y0.000 E15.236
G1 X-2.607 Y-0.847 E15.288
G1 X-2.217 Y-1.611 E15.339
G1 X-1.611 Y-2.217 E15.391
G1 X-0.847 Y-2.607 E15.442
G1 X0.000 Y-2.740 E15.494
G1 X0.847 Y-2.607 E15.545
G1 X1.611 Y-2.217 E15.596
G1 X2.217 Y-1.611 E15.648
G1 X2.607 Y-0.847 E15.699
G1 X2.741 Y0.000 E15.751
G1 X2.607 Y0.847 E15.802
G1 X2.217 Y1.611 E15.854
G1 X1.979 Y1.849 E15.874
G1 X2.556 Y2.556 F150.000
G1 F100.002
G1 X2.152 Y2.961 E15.908
G1 X1.131 Y3.481 E15.977
G1 X0.000 Y3.660 E16.046
G1 X-1.131 Y3.481 E16.114
G1 X-2.152 Y2.961 E16.183
G1 X-2.961 Y2.152 E16.252
G1 X-3.481 Y1.131 E16.320
G1 X-3.660 Y-0.000 E16.389
G1 X-3.481 Y-1.131 E16.458
G1 X-2.961 Y-2.152 E16.527
G1 X-2.152 Y-2.961 E16.595
G1 X-1.131 Y-3.481 E16.664
G1 X-0.000 Y-3.660 E16.733
G1 X1.131 Y-3.481 E16.801
G1 X2.152 Y-2.961 E16.870
G1 X2.961 Y-2.152 E16.939
G1 X3.481 Y-1.131 E17.008
G1 X3.660 Y0.000 E17.076
G1 X3.481 Y1.131 E17.145
G1 X2.961 Y2.152 E17.214
G1 X2.621 Y2.492 E17.243
G1 X2.235 Y2.235 F150.000
G1 F150
G1 X1.881 Y2.588 E17.273
G1 X0.989 Y3.043 E17.333
G1 X-0.000 Y3.199 E17.393
G1 X-0.989 Y3.043 E17.453
G1 X-1.881 Y2.588 E17.513
G1 X-2.588 Y1.881 E17.573
G1 X-3.049 Y0.959 E17.635
G1 X-3.199 Y-0.000 E17.693
G1 X-3.049 Y-0.959 E17.751
G1 X-2.588 Y-1.881 E17.813
G1 X-1.881 Y-2.588 E17.873
G1 X-0.959 Y-3.049 E17.935
G1 X-0.000 Y-3.199 E17.993
G1 X0.959 Y-3.049 E18.051
G1 X1.881 Y-2.588 E18.113
G1 X2.588 Y-1.881 E18.173
G1 X3.030 Y-1.016 E18.232
G1 X3.199 Y-0.000 E18.293
G1 X3.043 Y0.989 E18.353
G1 X2.588 Y1.881 E18.413
G1 X2.300 Y2.170 E18.438
G1 Z3.600 F150.000
G1 X1.914 Y1.914 F150.000
G1 F100.002
G1 X1.611 Y2.217 E18.464
G1 X0.847 Y2.607 E18.515
G1 X0.000 Y2.741 E18.567
G1 X-0.847 Y2.607 E18.618
G1 X-1.611 Y2.217 E18.669
G1 X-2.217 Y1.611 E18.721
G1 X-2.607 Y0.847 E18.772
G1 X-2.741 Y0.000 E18.824
G1 X-2.607 Y-0.847 E18.875
G1 X-2.217 Y-1.611 E18.927
G1 X-1.611 Y-2.217 E18.978
G1 X-0.847 Y-2.607 E19.030
G1 X0.000 Y-2.740 E19.081
G1 X0.847 Y-2.607 E19.133
G1 X1.611 Y-2.217 E19.184
G1 X2.217 Y-1.611 E19.235
G1 X2.607 Y-0.847 E19.287
G1 X2.741 Y0.000 E19.338
G1 X2.607 Y0.847 E19.390
G1 X2.217 Y1.611 E19.441
G1 X1.979 Y1.849 E19.461
G1 X2.556 Y2.556 F150.000
G1 F100.002
G1 X2.152 Y2.961 E19.496
G1 X1.131 Y3.481 E19.565
G1 X-0.000 Y3.660 E19.633
G1 X-1.131 Y3.481 E19.702
G1 X-2.152 Y2.961 E19.771
G1 X-2.961 Y2.152 E19.839
G1 X-3.481 Y1.131 E19.908
G1 X-3.660 Y0.000 E19.977
G1 X-3.481 Y-1.131 E20.045
G1 X-2.961 Y-2.152 E20.114
G1 X-2.152 Y-2.961 E20.183
G1 X-1.131 Y-3.481 E20.252
G1 X0.000 Y-3.660 E20.320
G1 X1.131 Y-3.481 E20.389
G1 X2.152 Y-2.961 E20.458
G1 X2.961 Y-2.152 E20.526
G1 X3.481 Y-1.131 E20.595
G1 X3.660 Y-0.000 E20.664
G1 X3.481 Y1.131 E20.733
G1 X2.961 Y2.152 E20.801
G1 X2.621 Y2.492 E20.830
G1 X2.235 Y2.235 F150.000
G1 F150
G1 X1.881 Y2.588 E20.860
G1 X0.989 Y3.043 E20.920
G1 X-0.000 Y3.199 E20.980
G1 X-0.989 Y3.043 E21.040
G1 X-1.881 Y2.588 E21.100
G1 X-2.588 Y1.881 E21.160
G1 X-3.049 Y0.959 E21.222
G1 X-3.199 Y0.000 E21.281
G1 X-3.049 Y-0.959 E21.339
G1 X-2.588 Y-1.881 E21.401
G1 X-1.881 Y-2.588 E21.461
G1 X-0.959 Y-3.049 E21.522
G1 X0.000 Y-3.199 E21.581
G1 X0.959 Y-3.049 E21.639
G1 X1.881 Y-2.588 E21.701
G1 X2.588 Y-1.881 E21.761
G1 X3.030 Y-1.016 E21.819
G1 X3.199 Y-0.000 E21.881
G1 X3.043 Y0.989 E21.941
G1 X2.588 Y1.881 E22.001
G1 X2.300 Y2.170 E22.026
G1 Z4.200 F150.000
G1 X1.914 Y1.914 F150.000
G1 F100.002
G1 X1.611 Y2.217 E22.051
G1 X0.847 Y2.607 E22.103
G1 X0.000 Y2.741 E22.154
G1 X-0.847 Y2.607 E22.206
G1 X-1.611 Y2.217 E22.257
G1 X-2.217 Y1.611 E22.308
G1 X-2.607 Y0.847 E22.360
G1 X-2.741 Y0.000 E22.411
G1 X-2.607 Y-0.847 E22.463
G1 X-2.216 Y-1.614 E22.515
G1 X-1.611 Y-2.217 E22.566
G1 X-0.847 Y-2.607 E22.617
G1 X-0.029 Y-2.736 E22.667
G1 X0.845 Y-2.608 E22.720
G1 X1.611 Y-2.217 E22.772
G1 X2.217 Y-1.611 E22.823
G1 X2.607 Y-0.847 E22.874
G1 X2.741 Y0.000 E22.926
G1 X2.607 Y0.847 E22.977
G1 X2.217 Y1.611 E23.029
G1 X1.979 Y1.849 E23.049
G1 X2.556 Y2.556 F150.000
G1 F100.002
G1 X2.152 Y2.961 E23.083
G1 X1.131 Y3.481 E23.152
G1 X-0.000 Y3.660 E23.221
G1 X-1.131 Y3.481 E23.289
G1 X-2.152 Y2.961 E23.358
G1 X-2.961 Y2.152 E23.427
G1 X-3.481 Y1.131 E23.496
G1 X-3.660 Y-0.000 E23.564
G1 X-3.481 Y-1.131 E23.633
G1 X-2.961 Y-2.152 E23.702
G1 X-2.152 Y-2.961 E23.770
G1 X-1.131 Y-3.481 E23.839
G1 X0.000 Y-3.660 E23.908
G1 X1.131 Y-3.481 E23.977
G1 X2.152 Y-2.961 E24.045
G1 X2.961 Y-2.152 E24.114
G1 X3.481 Y-1.131 E24.183
G1 X3.660 Y-0.000 E24.251
G1 X3.481 Y1.131 E24.320
G1 X2.961 Y2.152 E24.389
G1 X2.621 Y2.492 E24.418
G1 X2.235 Y2.235 F150.000
G1 F150
G1 X1.881 Y2.588 E24.448
G1 X0.989 Y3.043 E24.508
G1 X-0.000 Y3.199 E24.568
G1 X-0.989 Y3.043 E24.628
G1 X-1.881 Y2.588 E24.688
G1 X-2.588 Y1.881 E24.748
G1 X-3.049 Y0.959 E24.810
G1 X-3.199 Y-0.000 E24.868
G1 X-3.049 Y-0.959 E24.926
G1 X-2.588 Y-1.881 E24.988
G1 X-1.880 Y-2.588 E25.048
G1 X-0.959 Y-3.049 E25.110
G1 X0.000 Y-3.196 E25.168
G1 X0.954 Y-3.050 E25.226
G1 X1.880 Y-2.588 E25.288
G1 X2.588 Y-1.881 E25.348
G1 X3.030 Y-1.016 E25.407
G1 X3.199 Y-0.000 E25.468
G1 X3.043 Y0.989 E25.528
G1 X2.588 Y1.881 E25.588
G1 X2.300 Y2.170 E25.613
G1 E27.113 F2400.00000
G92 E0
G1 Z4.350 F150.000
M107
; Filament-specific end gcode 
;END gcode for filament

G1 X0 Y0 Z20 F500
M84       ;Motors off
M104 S0 ; set temperature
M140 S0 ; set bed temperature
; filament used = 9.4mm (0.2cm3)
; total filament cost = 0.0

; avoid_crossing_perimeters = 1
; bed_shape = -81x-81,81x-81,81x81,-81x81
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = G1 X0 Y0 Z20 F500\nM84       ;Motors off
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1.4
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #FFFFFF
; filament_cost = 0
; filament_density = 0
; filament_diameter = 4.6
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0
; first_layer_speed = 1.6667
; first_layer_temperature = 0
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; has_heatbed = 1
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 10
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.0001
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.61
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; printer_notes = 
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 0.75
; retract_length_toolchange = 10
; retract_lift = 0.15
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = T0\nG92 X0 Y0 Z0 E0  ;set coordinates to 0 \nG92 E0\n\nT0\nM302 P1
; temperature = 0
; threads = 8
; toolchange_gcode = 
; travel_speed = 2.5
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_set_and_wait_bed = 0
; use_set_and_wait_extruder = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 0
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.6
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.6
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = aligned
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_max_layers = 0
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 0
; bridge_flow_ratio = 1
; bridge_speed = 2.5
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 1.6667
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 50%
; fill_gaps = 1
; fill_pattern = rectilinear
; gap_fill_speed = 2.5
; infill_every_layers = 10
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 15%
; infill_speed = 2.5
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 1.6667
; perimeters = 1
; small_perimeter_speed = 1.6667
; solid_infill_below_area = 5
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 15
; top_solid_layers = 0




